apiVersion: apps/v1
kind: Deployment
metadata:
  name: muze-web
  namespace: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: muze-web
  template:
    metadata:
      labels:
        app: muze-web
    spec:
      serviceAccountName: muze-web-sa
      containers:
        - name: muze-web
          image: 620455725858.dkr.ecr.ap-northeast-2.amazonaws.com/muze:v9
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: muze-app-secrets
      imagePullSecrets:
        - name: ecr-secret
