apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: muze-web-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/load-balancer-name: muze-prod-alb
    alb.ingress.kubernetes.io/group.name: muze-prod-group
    alb.ingress.kubernetes.io/group.order: '10'


    alb.ingress.kubernetes.io/actions.ssl-redirect: >
      {"Type": "redirect", "RedirectConfig":
        {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:620455725858:certificate/d980c0cb-8540-4d44-bf77-46c527df9e7b
    external-dns.alpha.kubernetes.io/hostname: www.muz-e.com

spec:
  ingressClassName: alb
  rules:
  - host: www.muz-e.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation

      - path: /
        pathType: Prefix
        backend:
          service:
            name: muze-web-svc
            port:
              number: 80

